version: '3.1'

services:

  db:
    image: mariadb
    container_name: sb_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: socialmedia